/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biruarenrollmentsystem;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asian
 */
public class GradesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GradesForm.class.getName());

    /**
     * Creates new form GradesForm
     */
    public GradesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradesFormLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        studidTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        prelimComboBox = new javax.swing.JComboBox<>();
        midComboBox = new javax.swing.JComboBox<>();
        prefComboBox = new javax.swing.JComboBox<>();
        finalComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        gradesFormLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gradesFormLabel.setText("Teacher Class List/Grades Encoding Form:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "StudID", "Name", "Prelim", "Midterms", "PreFinal", "Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable3);

        studidTextField.setEditable(false);
        studidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidTextFieldActionPerformed(evt);
            }
        });

        nameTextField.setEditable(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        prelimComboBox.setToolTipText("");

        midComboBox.setSelectedItem(null);
        midComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("StudID");

        jLabel2.setText("Name");

        jLabel3.setText("Prelim");

        jLabel4.setText("Midterms");

        jLabel5.setText("PreFinal");

        jLabel6.setText("Final");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "subjid", "SubjCode", "SubjDesc", "SubjUnits", "Schedule", "Students"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Student Evaluation");

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prelimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(midComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(prefComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalComboBox, 0, 89, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(showButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(gradesFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(gradesFormLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showButton)
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prelimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prefComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(midComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        String studid = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
        String name = jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
        
        studidTextField.setText(studid);
        nameTextField.setText(name);
        try{
            prelimComboBox.setSelectedItem(jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString());
            midComboBox.setSelectedItem(jTable3.getValueAt(jTable3.getSelectedRow(), 3).toString());
            prefComboBox.setSelectedItem(jTable3.getValueAt(jTable3.getSelectedRow(), 4).toString());
            finalComboBox.setSelectedItem(jTable3.getValueAt(jTable3.getSelectedRow(), 5).toString());
        } catch(Exception ex){
            System.out.println("Prelim to Finals are empty");
        }
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void studidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        //schoolYearDropDown.setModel(model);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> model3 = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> model4 = new DefaultComboBoxModel<>();
        
        model.addElement("A");
        model.addElement("B+");
        model.addElement("B");
        model.addElement("C+");
        model.addElement("C");
        model.addElement("D");
        model.addElement("F");
        model.addElement("FD");
        
        model2.addElement("A");
        model2.addElement("B+");
        model2.addElement("B");
        model2.addElement("C+");
        model2.addElement("C");
        model2.addElement("D");
        model2.addElement("F");
        model2.addElement("FD");
        
        model3.addElement("A");
        model3.addElement("B+");
        model3.addElement("B");
        model3.addElement("C+");
        model3.addElement("C");
        model3.addElement("D");
        model3.addElement("F");
        model3.addElement("FD");
        
        model4.addElement("A");
        model4.addElement("B+");
        model4.addElement("B");
        model4.addElement("C+");
        model4.addElement("C");
        model4.addElement("D");
        model4.addElement("F");
        model4.addElement("FD");
        
        prelimComboBox.setModel(model);
        prelimComboBox.setSelectedIndex(-1);
        midComboBox.setModel(model2);
        midComboBox.setSelectedIndex(-1);
        prefComboBox.setModel(model3);
        prefComboBox.setSelectedIndex(-1);
        finalComboBox.setModel(model4);
        finalComboBox.setSelectedIndex(-1);
        
        Enrolled a = new Enrolled();
        String subjid = (String) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        a.setsubjid(Integer.parseInt(subjid));
        
        showGrades();
        
    }//GEN-LAST:event_jTable2MouseClicked

    
    public void showGrades(){
        Grades a = new Grades();
        
        int subId = 0;
        int row1 = jTable2.getSelectedRow();
        if(row1 != -1){
            subId = Integer.parseInt(jTable2.getValueAt(row1, 0).toString());
            System.out.println("ID: " + subId);
        }

        String query = String.format(
                "SELECT s.studid,s.name,"
                + "(SELECT g.Prelim FROM `%s`.grades g WHERE g.eid=e.eid) AS Prelim,"
                + "(SELECT g.Midterm FROM `%s`.grades g WHERE g.eid=e.eid) AS Midterm,"
                + "(SELECT g.Prefinal FROM `%s`.grades g WHERE g.eid=e.eid) AS Prefinal,"
                + "(SELECT g.Final FROM `%s`.grades g WHERE g.eid=e.eid) AS Final "
                + "FROM `%s`.students s,`%s`.enroll e "
                + "WHERE s.studid=e.studid AND e.subjid=%d;",
                a.db, a.db, a.db, a.db, a.db, a.db, subId
        );
        DefaultTableModel model = ((DefaultTableModel) jTable3.getModel());
        model.setRowCount(0);
        try{
            a.rs = a.st.executeQuery(query);
            while(a.rs.next()){
                String studid = a.rs.getString("studid");
                String name = a.rs.getString("name");
                String prel = a.rs.getString("Prelim") == null ? "" : a.rs.getString("Prelim").equalsIgnoreCase("null") ? "" : a.rs.getString("Prelim");
                String mid = a.rs.getString("Midterm") == null ? "" : a.rs.getString("Midterm").equalsIgnoreCase("null") ? "" : a.rs.getString("Midterm");
                String pref = a.rs.getString("Prefinal") == null ? "" : a.rs.getString("Prefinal").equalsIgnoreCase("null") ? "" : a.rs.getString("Prefinal");;
                String finalGrade = a.rs.getString("Final") == null ? "" : a.rs.getString("Final").equalsIgnoreCase("null") ? "" : a.rs.getString("Final");
                String[] items = {studid, name, prel, mid, pref, finalGrade};
                model.addRow(items);
            }
        } catch(SQLException ex){
            query = String.format(
                "SELECT s.studid,s.name,"
                + "(SELECT NULL FROM null g WHERE g.eid=e.eid) AS Prelim,"
                + "(SELECT NULL FROM `%s`.grades g WHERE g.eid=e.eid) AS Midterm,"
                + "(SELECT NULL FROM `%s`.grades g WHERE g.eid=e.eid) AS Prefinal,"
                + "(SELECT NULL FROM `%s`.grades g WHERE g.eid=e.eid) AS Final "
                + "FROM `%s`.students s,`%s`.enroll e "
                + "WHERE s.studid=e.studid AND e.subjid=%d;",
                a.db, a.db, a.db, a.db, a.db, a.db, subId
        );
            try{
            a.rs = a.st.executeQuery(query);
            while(a.rs.next()){
                String studid = a.rs.getString("studid");
                String name = a.rs.getString("name");
                String prel = a.rs.getString("Prelim");
                String mid = a.rs.getString("Midterm");
                String pref = a.rs.getString("Prefinal");
                String finalGrade = a.rs.getString("Final");
                String[] items = {studid, name, prel, mid, pref, finalGrade};
                model.addRow(items);
              }
            }
            catch(SQLException ex3){
                    System.out.println("Unable to display students enrolled ex: " + ex);
                    }
            
            System.out.println("Unable to display students enrolled ex: " + ex);
        }
        
    }
    
    public void showSubj(){
        Teachers a = new Teachers();
        //SELECT s.subjid, s.subjcode, s.subjdesc, s.subjunits, s.schedule, (SELECT count(e.studid) 
        //from enroll e where s.subjid = e.subjid) as Students FROM subjects s WHERE subjid in (SELECT subid FROM assign WHERE tid = 3001);
        
        String query = String.format("SELECT s.subjid, s.subjcode, s.subjdesc, s.subjunits, s.schedule, "
                + "(SELECT count(e.studid) from `%s`.enroll e where s.subjid = e.subjid) as Students FROM `%s`.subjects s WHERE subjid in (SELECT subid FROM `%s`.assign "
                + "WHERE tid = %s);", a.db, a.db,a.db,a.uname.substring(0,4)); //3001aa
        DefaultTableModel model = ((DefaultTableModel) jTable2.getModel());
        model.setRowCount(0);

        try{
            a.rs = a.st.executeQuery(query);
            while(a.rs.next()){
                String id = a.rs.getString("subjid");
                String code = a.rs.getString("subjcode");
                String desc = a.rs.getString("subjdesc");
                String units = a.rs.getString("subjunits");
                String sched = a.rs.getString("schedule");
                String students = a.rs.getString("Students");
                String[] items = {id, code, desc, units, sched, students};
                model.addRow(items);
            }
            
        } catch(SQLException ex){
            System.out.println("Ex: " + ex);
        }
        
    } //ask sir
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Grades a = new Grades();
        Enrolled b = new Enrolled();
        int eid = -1;
        int id = Integer.parseInt(studidTextField.getText());
        String query = String.format("SELECT eid FROM enroll WHERE studid = %d AND subjid = %d;", id, b.getsubjid());
            System.out.println(id + " " + b.getsubjid());
            try{
                b.rs = b.st.executeQuery(query);
                while(b.rs.next()){
                    eid = b.rs.getInt("eid");
                }
            }catch(SQLException ex){
                System.out.println(ex);
            }
        
        String prel = (String) prelimComboBox.getSelectedItem();
        String mid = (String) midComboBox.getSelectedItem();
        String pref = (String) prefComboBox.getSelectedItem();
        String finalGrade = (String) finalComboBox.getSelectedItem();
        
        try{
            a.insert(eid, prel, mid, pref, finalGrade);
        }
        catch(SQLException ex2){
            System.out.println("Error GradesForm SAVE tried INSERT: " + ex2);
        }
        showGrades();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void midComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midComboBoxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        gradesFormLabel.setText("Teacher Class List/Grades Encoding Form: " + BiruarEnrollmentSystem.db);
        showSubj();
    }//GEN-LAST:event_formWindowOpened

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        String subjid = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        evaluationForm a = new evaluationForm(subjid);
        a.setVisible(true);
    }//GEN-LAST:event_showButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GradesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> finalComboBox;
    private javax.swing.JLabel gradesFormLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> midComboBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> prefComboBox;
    private javax.swing.JComboBox<String> prelimComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField studidTextField;
    // End of variables declaration//GEN-END:variables
}
