/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biruarenrollmentsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.TreeSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author asian
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        schoolYearDropDown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        schoolYearDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School Year" }));
        schoolYearDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoolYearDropDownMouseClicked(evt);
            }
        });
        schoolYearDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolYearDropDownActionPerformed(evt);
            }
        });

        jLabel3.setText("School Year");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(schoolYearDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(loginButton)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolYearDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(submitButton)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void schoolYearDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolYearDropDownActionPerformed
        // TODO add your handling code here:
        //BiruarEnrollmentSystem BRS = new BiruarEnrollmentSystem();
    }//GEN-LAST:event_schoolYearDropDownActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

            // TODO add your handling code here:
            String uName = username.getText();
            char[] pass = jPasswordField1.getPassword();
            String ps = new String(pass);
            Arrays.fill(pass, '\0');
            
            BiruarEnrollmentSystem BRS = new BiruarEnrollmentSystem();
            
            try{
                String serverUrl = "jdbc:mysql://localhost:3306/?zeroDateTimeBehavior=CONVERT_TO_NULL";
                BRS.con = DriverManager.getConnection(serverUrl, uName, ps);
                BRS.st  = BiruarEnrollmentSystem.con.createStatement();
                BRS.uname = uName;
                BRS.pswd = ps;
                JOptionPane.showMessageDialog(null, "Successful login");
                
                String type = uName.startsWith("r") || uName.startsWith("R") ? "root"
                        : uName.startsWith("3") ? "teacher" : "student";

                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                
                //list available schema for curent user
                final String listAySchemasSql = """
                SELECT SCHEMA_NAME
                FROM information_schema.SCHEMATA
                WHERE SCHEMA_NAME REGEXP '^(1st|2nd|summer)_sy[0-9]{4}_[0-9]{4}$'
                ORDER BY SCHEMA_NAME
                """;
                
                ResultSet rsListDataBase = BRS.st.executeQuery(listAySchemasSql);
                TreeSet <String> availDb = new TreeSet<String>(); 
                while(rsListDataBase.next()){
                    String database = rsListDataBase.getString(1);
                    availDb.add(database);
                }
                //BRS.rs = BRS.st.executeQuery(listAySchemasSql);
                if(type.equals("student")){
                    String sql = "SHOW GRANTS;";
                    Statement st2 = BRS.st;
                    BRS.rs = st2.executeQuery(sql);
                    
                    while(BRS.rs.next()){
                        String grant = BRS.rs.getString(1);
                        for(String dbName : availDb){
                            if(grant.contains(dbName) && grant.contains("SELECT") && !grant.contains("UPDATE") && !grant.contains("INSERT"))
                                model.addElement(dbName);
                        }
                    }
                }
                else if(type.equals("teacher")){
                    String sql = "SHOW GRANTS;";
                    Statement st2 = BRS.st;
                    BRS.rs = st2.executeQuery(sql);
                    
                    while(BRS.rs.next()){
                        String grant = BRS.rs.getString(1);
                        for(String dbName : availDb){
                            if(grant.contains(dbName) && grant.contains("SELECT") && grant.contains("UPDATE") && grant.contains("INSERT"))
                                model.addElement(dbName);
                        }
                    }
                }
                else{
                    for(String dbName : availDb)
                        model.addElement(dbName);
                }
                schoolYearDropDown.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Wrong username or password");
            schoolYearDropDown.removeAllItems();
            return;
        } 
    }//GEN-LAST:event_loginButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String select = (String) schoolYearDropDown.getSelectedItem();
        
        try(Statement s = BiruarEnrollmentSystem.con.createStatement()){
            s.execute("USE `" + select +"`;");
            BiruarEnrollmentSystem.db = select;
            
            BiruarEnrollmentSystem.st = BiruarEnrollmentSystem.con.createStatement();
            String type = username.getText().startsWith("r") || username.getText().startsWith("R") ? "root" : 
                    username.getText().startsWith("3") ? "teacher" : "student";
            
            if(type.equalsIgnoreCase("root")){
                StudentsForm a = new StudentsForm();
                a.setVisible(true);
            } 
            else if(type.equalsIgnoreCase("teacher")){
                GradesForm a = new GradesForm();
                a.setVisible(true);
            } else{
                Reports a = new Reports();
                int studid = Integer.parseInt(a.uname.substring(0, 4));
                String uName = a.uname.substring(4);

                a.createStudReport(studid, uName);
            }
             System.out.println("Connected to DB (ignore false flag below): " + BiruarEnrollmentSystem.db);
        } 
        //
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,
                    "You don't have access to " + select + ":\n" + ex.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void schoolYearDropDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolYearDropDownMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_schoolYearDropDownMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JComboBox<String> schoolYearDropDown;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
