/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biruarenrollmentsystem;

import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.con;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.db;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.pswd;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.st;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.uname;
//import static com.mycompany.biruarenrollmentsystem.Utility.createDB;
//import static com.mycompany.biruarenrollmentsystem.Utility.loadRecord;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.awt.List;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.time.Year;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import weka.classifiers.trees.J48;
import weka.core.Instances;
import weka.core.SerializationHelper;
import static weka.core.Utils.maxIndex;
import weka.experiment.InstanceQuery;
import org.optaplanner.core.api.solver.Solver;
import org.optaplanner.core.api.solver.SolverFactory;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import org.optaplanner.core.config.score.director.ScoreDirectorFactoryConfig;
import org.optaplanner.core.config.solver.SolverConfig;
import org.optaplanner.core.config.solver.termination.TerminationConfig;

/**
 *
 * @author mxebiruar
 */
public class StudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        studid = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Course = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        studRegLabel = new javax.swing.JLabel();
        Yearlvl = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        aiEnrollButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TORbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        aiMenu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        studid.setEditable(false);
        studid.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        studid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studidActionPerformed(evt);
            }
        });

        Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseActionPerformed(evt);
            }
        });

        jLabel1.setText("Student ID");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel5.setText("Course");

        jLabel6.setText("Gender");

        jLabel7.setText("Student Year Level");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setAutoscrolls(true);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Course", "Gender", "Student Year Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        studRegLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studRegLabel.setForeground(new java.awt.Color(0, 153, 255));
        studRegLabel.setText("Student Registration");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "subjid", "SubjCode", "SubjDesc", "SubjUnits", "Schedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButton4.setText("Enroll Subject");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Drop Subject");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        aiEnrollButton.setText("AI Enroll");
        aiEnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiEnrollButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(aiEnrollButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(aiEnrollButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );

        jLabel9.setText("Enrolled");

        jLabel4.setText("Print");

        TORbutton.setText("TOR");
        TORbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TORbuttonActionPerformed(evt);
            }
        });

        jMenu1.setText("Form");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Teachers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem8.setText("Subjects");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Database");

        jMenuItem5.setText("1st Semester");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("2nd Semester");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Summer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        aiMenu.setText("AI");

        jMenuItem9.setText("Train Enrolled Subjects");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        aiMenu.add(jMenuItem9);

        jMenuItem10.setText("Optaplanner Conflict");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        aiMenu.add(jMenuItem10);

        jMenuBar1.add(aiMenu);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(Course, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Address, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Yearlvl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(TORbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studRegLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(studRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Yearlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TORbutton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studidActionPerformed

    private void CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TeachersForm a = new TeachersForm();
        a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private String getPreviousSchema(String currentSchema) {
    // Example: 1st_sy2026_2027
    String[] parts = currentSchema.split("_");
    String sem = parts[0]; // 1st / 2nd / summer
    int start = Integer.parseInt(parts[1].substring(2, 6));
    int end = Integer.parseInt(parts[2]);
    
    System.out.println("summer_sy" + (start-1) + "_" + (end-1));
    
    switch (sem.toLowerCase()) {
        case "1st":  return "summer_sy" + (start - 1) + "_" + (end - 1);
        case "2nd":  return "1st_sy" + start + "_" + end;
        case "summer": return "2nd_sy" + start + "_" + end;
        default: return null;
    }
  }
    
   
    public void studTeachSubCopy(String currSy) throws Exception {
    try {
        // 1. Find previous schema
        String prevSchema = getPreviousSchema(currSy);
        if (prevSchema == null) {
            System.out.println("⚠️ No previous schema found for: " + currSy);
            JOptionPane.showMessageDialog(null, "⚠️ No previous schema found for: " + currSy);
            return;
        }

        System.out.println("Copying from: " + prevSchema);

        // Copy Students
        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM `" + prevSchema + "`.students")) {
            while (rs.next()) {
                String studid = rs.getString("studid");
                String name = rs.getString("Name");
                String address = rs.getString("Address");
                String course = rs.getString("Course");
                String gender = rs.getString("Gender");
                String yearLevel = rs.getString("Yearlvl");

                String sql = "INSERT INTO `" + currSy + "`.Students (studid, Name, Address, Course, Gender, Yearlvl) "
                           + "VALUES (" + studid + ",'" + name + "','" + address + "','" + course + "','" + gender + "','" + yearLevel + "')";
                st.executeUpdate(sql);

                String newUserQuery = String.format(
                        "CREATE USER IF NOT EXISTS '%s'@'localhost' IDENTIFIED BY '%s';",
                        (Integer.parseInt(studid) + name), ("AdDU" + name));
                st.executeUpdate(newUserQuery);
                st.executeUpdate(String.format(
                        "GRANT SELECT ON `" + currSy + "`.* TO '%s'@'localhost';",
                        (Integer.parseInt(studid) + name)));

                System.out.println("Inserted Student " + studid);
            }
        }

        // Copy Teachers
        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM `" + prevSchema + "`.teachers")) {
            while (rs.next()) {
                String tid = rs.getString("Tid");
                String name = rs.getString("Name");
                String address = rs.getString("Address");
                String contact = rs.getString("Contact");
                String status = rs.getString("Status");
                String dept = rs.getString("Dept");

                String sql = "INSERT INTO `" + currSy + "`.Teachers (Tid, Name, Address, Contact, Status, Dept) "
                           + "VALUES (" + tid + ",'" + name + "','" + address + "','" + contact + "','" + status + "','" + dept + "')";
                st.executeUpdate(sql);

                String newUserQuery = String.format(
                        "CREATE USER IF NOT EXISTS '%s'@'localhost' IDENTIFIED BY '%s';",
                        (Integer.parseInt(tid) + name), ("AdDU" + name));
                st.executeUpdate(newUserQuery);
                st.executeUpdate(String.format(
                        "GRANT SELECT,UPDATE,INSERT ON `" + currSy + "`.* TO '%s'@'localhost';",
                        (Integer.parseInt(tid) + name)));

                System.out.println("Inserted Teacher " + tid);
            }
        }

        // Copy Subjects
        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM `" + prevSchema + "`.subjects")) {
            while (rs.next()) {
                String id = rs.getString("subjid");
                String code = rs.getString("SubjCode");
                String desc = rs.getString("SubjDesc");
                String units = rs.getString("SubjUnits");
                String sched = rs.getString("Schedule");

                String sql = String.format(
                        "INSERT INTO `%s`.Subjects VALUES ('%s', '%s', '%s', '%s', '%s');",
                        currSy, id, code, desc, units, sched);
                st.executeUpdate(sql);

                System.out.println("Inserted Subject " + id);
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
           
         //createDB("1st");
        Students a = new Students();
        
        String getMax = "SELECT schema_name "
                + "FROM information_schema.schemata "
                + "WHERE schema_name REGEXP '^1st_sy[0-9]{4}_[0-9]{4}$' "
                + "ORDER BY schema_name DESC "
                + "LIMIT 1";
        String input = "";
        
        try {
            a.rs = a.st.executeQuery(getMax);
            
            while(a.rs.next())
                input = a.rs.getString("SCHEMA_NAME");
        } catch (SQLException ex) {
            System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        int currYear = 0; // where we'll save the result

        String patternString = "sy(\\d{4})"; // regex pattern
        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(input);

        if (matcher.find()) {
            currYear = Integer.parseInt(matcher.group(1)) + 1; // save "2025" into the string variable
        }

        int nextYear = currYear + 1;
        String dbName = "1st" + "_sy" + currYear + "_" + nextYear;

        String sql = "CREATE DATABASE `" + dbName + "`;";
        
        try {
            try (Statement stmt = con.createStatement()) {
                
                //create new database
                
                stmt.executeUpdate(sql);
                String origDB = a.db;
                String tempDBUSE = "USE `" + dbName + "`;";
                String backDB = "USE `" + origDB+ "`;";
                stmt.executeUpdate(tempDBUSE);

                //create student table
                sql = "CREATE TABLE students ("
                        + "studid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Course TEXT, "
                        + "Gender TEXT, "
                        + "Yearlvl TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create teacher's table
                sql = "CREATE TABLE teachers ("
                        + "Tid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Contact TEXT, "
                        + "Status TEXT, "
                        + "Dept TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create subjects table
                sql = "CREATE TABLE subjects ("
                        + "subjid INT PRIMARY KEY, "
                        + "SubjCode TEXT, "
                        + "SubjDesc TEXT, "
                        + "SubjUnits INT, "
                        + "Schedule TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create enroll
                sql = "CREATE TABLE enroll ("
                        + "eid INT PRIMARY KEY, "
                        + "studid INT, "
                        + "subjid INT, "
                        + "evaluation TEXT, "
                        + "FOREIGN KEY (studid) REFERENCES Students(studid),"
                        + "FOREIGN KEY (subjid) REFERENCES Subjects(subjid),"
                        + "UNIQUE (studid, subjid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create assign
                sql = "CREATE TABLE assign ("
                        + "subid INT, "
                        + "tid INT, "
                        + "FOREIGN KEY (subid) REFERENCES Subjects(subjid),"
                        + "FOREIGN KEY (tid) REFERENCES Teachers(Tid),"
                        + "UNIQUE (subid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create grades
                sql = "CREATE TABLE grades ("
                        + "GradeID INT PRIMARY KEY, "
                        + "eid INT, "
                        + "Prelim TEXT,"
                        + "Midterm TEXT, "
                        + "Prefinal TEXT, "
                        + "Final TEXT,"
                        + "FOREIGN KEY (eid) REFERENCES Enroll(eid),"
                        + "UNIQUE (eid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create TransactionCharges table
                sql = "CREATE TABLE TransactionCharges ("
                        + "TransID INT PRIMARY KEY, "
                        + "Department TEXT, "
                        + "SubjUnits DECIMAL(10,2), "
                        + "Insurance DECIMAL(10,2), "
                        + "Computer DECIMAL(10,2), "
                        + "Laboratory DECIMAL(10,2), "
                        + "Cultural DECIMAL(10,2), "
                        + "Library DECIMAL(10,2), "
                        + "Facility DECIMAL(10,2)"
                        + ");";
                stmt.executeUpdate(sql);

                //create invoice
                sql = "CREATE TABLE Invoice ("
                        + "Invoicenum INT PRIMARY KEY, "
                        + "studid INT, "
                        + "TransID INT,"
                        + "FOREIGN KEY(TransID) REFERENCES TransactionCharges(TransID),"
                        + "FOREIGN KEY(studid) REFERENCES Students(studid),"
                        + "UNIQUE (TransID)"
                        + ");";
                stmt.executeUpdate(sql);
                
                /*
                String dropProc = "DROP PROCEDURE IF EXISTS sched_Conf";
                st.executeUpdate(dropProc);
                */
                sql = """
                     CREATE PROCEDURE sched_Conf(IN studId INT, IN subid2 INT)
                     BEGIN
                         DECLARE subSched VARCHAR(20);
                         DECLARE subDays VARCHAR(10);
                         DECLARE subHoursStart VARCHAR(10);
                         DECLARE subMinutesStart VARCHAR(10);
                         DECLARE subHoursEnd VARCHAR(10);
                         DECLARE subMinutesEnd VARCHAR(10);
                         DECLARE subSched2 VARCHAR(20);
                         DECLARE subDays2 VARCHAR(10);
                         DECLARE subHoursStart2 VARCHAR(10);
                         DECLARE subMinutesStart2 VARCHAR(10);
                         DECLARE subHoursEnd2 VARCHAR(10);
                         DECLARE subMinutesEnd2 VARCHAR(10);
                         DECLARE noMoreSched INT DEFAULT 0;
                         DECLARE curSub CURSOR FOR
                             SELECT s.schedule
                             FROM enroll e
                             INNER JOIN subjects s ON e.subjid = s.subjid
                             WHERE e.studid = studId;
                         DECLARE curSub2 CURSOR FOR
                             SELECT schedule FROM subjects WHERE subjid = subid2;
                         DECLARE CONTINUE HANDLER FOR NOT FOUND SET noMoreSched = 1;
                         CREATE TEMPORARY TABLE conflicts (studid INT, subjid INT);
                         CREATE TABLE IF NOT EXISTS conflictMsg (msg VARCHAR(50));
                         DELETE FROM conflictMsg;
                         OPEN curSub;
                         sub1_loop: LOOP
                             FETCH curSub INTO subSched;
                             IF noMoreSched THEN
                                 LEAVE sub1_loop;
                             END IF;
                             SET subDays        = LEFT(subSched, 3);
                             SET subHoursStart  = SUBSTRING(subSched, 5, 2);
                             SET subMinutesStart= SUBSTRING(subSched, 8, 2);
                             SET subHoursEnd    = SUBSTRING(subSched, 11, 2);
                             SET subMinutesEnd  = SUBSTRING(subSched, 14, 2);
                             SET noMoreSched = 0;
                             OPEN curSub2;
                             sub2_loop: LOOP
                                 FETCH curSub2 INTO subSched2;
                                 IF noMoreSched THEN
                                     LEAVE sub2_loop;
                                 END IF;
                                 SET subDays2         = LEFT(subSched2, 3);
                                 SET subHoursStart2   = SUBSTRING(subSched2, 5, 2);
                                 SET subMinutesStart2 = SUBSTRING(subSched2, 8, 2);
                                 SET subHoursEnd2     = SUBSTRING(subSched2, 11, 2);
                                 SET subMinutesEnd2   = SUBSTRING(subSched2, 14, 2);
                                 SET @start1 = subHoursStart * 100 + subMinutesStart;
                                 SET @end1   = subHoursEnd   * 100 + subMinutesEnd;
                                 SET @start2 = subHoursStart2 * 100 + subMinutesStart2;
                                 SET @end2   = subHoursEnd2   * 100 + subMinutesEnd2;
                                 IF subDays = subDays2 AND @start1 < @end2 AND @start2 < @end1 THEN
                                     INSERT INTO conflicts VALUES (studId, subid2);
                                     INSERT INTO conflictMsg VALUES (CONCAT('Conflict with schedule: ', subSched));
                                 END IF;
                             END LOOP sub2_loop;
                             CLOSE curSub2;
                             SET noMoreSched = 0;
                         END LOOP sub1_loop;
                         CLOSE curSub;
                         -- DELETE FROM enroll WHERE (studid, subjid) IN (SELECT studid, subjid FROM conflicts);
                         DROP TEMPORARY TABLE conflicts;
                     END;
                    """;
                stmt.executeUpdate(sql);
                
                
                Predictions b = new Predictions();
                try {
                    studTeachSubCopy(dbName);
                    System.out.println("studTeachSubCopy BEING USED");
                } catch (Exception ex) {
                    System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                stmt.executeUpdate(backDB);
            }
            JOptionPane.showMessageDialog(null, "Database `" + dbName + "` created successfully!");
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
         //createDB
         showrecords();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Students a = new Students();
        try { 
            a.SaveRecord(studid.getText(), Name.getText(), Address.getText(),
                    Course.getText(), Gender.getText(), Yearlvl.getText());   // TODO add your handling code here:
        } catch (SQLException ex) {
            System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        showrecords();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showrecords();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Students a = new Students();        // TODO add your handling code here:
            a.UpdateRecord(Integer.parseInt(studid.getText()), Name.getText(), Address.getText(), Course.getText(), Gender.getText(), Yearlvl.getText());
        showrecords();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Students a = new Students();        // TODO add your handling code here:
            a.DeleteRecord(Integer.parseInt(studid.getText()));
        showrecords();
        
        String query = "DELETE FROM Enroll WHERE studid =" + Integer.parseInt(studid.getText()) + ";";
        try {
            Enrolled.st.executeUpdate(query);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        int id = Integer.parseInt(studid.getText().trim());
        String name = Name.getText().trim();
        
        //student delete
        boolean exists = false;
        try (ResultSet rs = BiruarEnrollmentSystem.st.executeQuery("SHOW DATABASES")) {
            while (rs.next()) {
                String dbName = rs.getString("Database"); //get database name

                // only check AY databases
                if (!dbName.matches("^(1st|2nd|summer)_sy\\d{4}_\\d{4}$")) { //checks if it's 1st_sy20252026
                    continue;
                }

                String check = "SELECT 1 FROM `" + dbName + "`.Students WHERE studid = ? LIMIT 1";
                try (PreparedStatement ps = BiruarEnrollmentSystem.con.prepareStatement(check)) {
                    ps.setInt(1, id);
                    try (ResultSet r = ps.executeQuery()) {
                        if (r.next()) {
                            exists = true; // student still exists somewhere
                            break;
                        }
                    }
                } catch (SQLException ignore) {
                    // ignore missing tables/dbs
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error checking databases: " + ex);
        }

        if (!exists) {
            try {
                a.st.executeUpdate("DROP USER IF EXISTS '" + (id + name) + "'@'localhost';");
                System.out.println("User " + (id + name) + " dropped from MySQL.");
            } catch (SQLException ex) {
                System.out.println("Failed to delete user from mysql.user: " + ex);
            }
        } else {
            //REVOKE privilege_type [(column_list)] ON [object_type] privilege_level FROM user_account [, user_account] ...;
            String uName = id+name;
            String revokeQuery = String.format("REVOKE SELECT ON `" + db + "`.* FROM '%s'@'localhost';", uName);
            try {
                st.executeUpdate(revokeQuery);
                System.out.println("Student REVOKED on " + db);
            } catch (SQLException ex) {
                System.out.println("Error: " + ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        SubjectForm a = new SubjectForm();        // TODO add your handling code here:
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        JTextField[] a = {studid, Name, Address, Course, Gender, Yearlvl};
        
        //loadRecord(jTable1, a, evt.getPoint());      // TODO add your handling code here:
        Point point = evt.getPoint();
        int row = jTable1.rowAtPoint(point);
        int col = jTable1.columnAtPoint(point);
        if(col == 0){
            for(int i = 0; i < jTable1.getColumnCount()-3; i++){
                a[i].setText(String.valueOf(jTable1.getValueAt(row,i)));
            }
        }
        a[3].setText("");
        a[4].setText("");
        a[5].setText("");
        //loadRecord
        
        ShowEnrollRec();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        SubjectForm a = new SubjectForm();
        a.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Enrolled a = new Enrolled(); // TODO add your handling code here:
        int id = 0;
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            id = Integer.parseInt(String.valueOf(jTable1.getValueAt(row, 0)));
            System.out.println("ID: " + id);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a student first.");
            return;
        }

        try {
            if (optaPlannerActivator % 2 == 0) {
                System.out.println("Using legacy SQL conflict check.");
                a.checkConflict(id, a.getsubjid());
                a.rs = a.st.executeQuery("SELECT * FROM conflictMsg;");
                if (a.rs.next()) {
                    String msg = a.rs.getString("msg");
                    throw new Exception(msg);
                }
                // If no conflict, proceed to enroll
                a.st.executeUpdate(a.enrollStud(id));
                JOptionPane.showMessageDialog(null, String.format("Student %s enrolled to %d", id, a.getsubjid()), "enroll", JOptionPane.INFORMATION_MESSAGE);

            } else {
                //OPTAPLANNER-BASED CONFLICT CHECK 
                System.out.println("Using OptaPlanner for conflict check.");
                int subjidToEnroll = a.getsubjid();
                if (subjidToEnroll <= 0) {
                    JOptionPane.showMessageDialog(null, "Please select a subject to enroll.");
                    return;
                }

                // 1) Build the tiny problem from DB (same as yours) ...
                ArrayList<optaPlannerEnroll> enrollmentsForCheck = new ArrayList<>();
                DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");

                // current enrollments
                String currentEnrollmentQuery
                        = "SELECT s.Schedule FROM enroll e JOIN subjects s ON e.subjid = s.subjid WHERE e.studid = " + id;
                try (ResultSet rs = st.executeQuery(currentEnrollmentQuery)) {
                    while (rs.next()) {
                        String scheduleStr = rs.getString("Schedule");
                        Timeslot timeslot = parseScheduleStringToTimeslot(scheduleStr, timeFormatter);
                        if (timeslot != null) {
                            enrollmentsForCheck.add(new optaPlannerEnroll(id, timeslot));
                        }
                    }
                }
                // new subject timeslot
                String newSubjectQuery = "SELECT Schedule FROM subjects WHERE subjid = " + subjidToEnroll;
                try (ResultSet rs = st.executeQuery(newSubjectQuery)) {
                    if (rs.next()) {
                        String scheduleStr = rs.getString("Schedule");
                        Timeslot newTimeslot = parseScheduleStringToTimeslot(scheduleStr, timeFormatter);
                        if (newTimeslot != null) {
                            enrollmentsForCheck.add(new optaPlannerEnroll(id, newTimeslot));
                        }
                    }
                }

                //Problem instance
                EnrollmentSchedule problem = new EnrollmentSchedule(enrollmentsForCheck);

                //Configure solver
                SolverConfig solverConfig = new SolverConfig();
                solverConfig.setSolutionClass(EnrollmentSchedule.class);
                solverConfig.setEntityClassList(Collections.singletonList(DummyPlanningEntity.class));

                ScoreDirectorFactoryConfig scoreDirectorFactoryConfig = new ScoreDirectorFactoryConfig();
                scoreDirectorFactoryConfig.setEasyScoreCalculatorClass(
                        com.mycompany.biruarenrollmentsystem.EnrollmentEasyScoreCalculator.class
                );
                solverConfig.setScoreDirectorFactoryConfig(scoreDirectorFactoryConfig);

                //Give it a few seconds to actually solve
                TerminationConfig terminationConfig = new TerminationConfig();
                // If your version supports Duration:
                terminationConfig.setSpentLimit(java.time.Duration.ofSeconds(5));
                solverConfig.setTerminationConfig(terminationConfig);

                SolverFactory<EnrollmentSchedule> solverFactory = SolverFactory.create(solverConfig);
                Solver<EnrollmentSchedule> solver = solverFactory.buildSolver();
                EnrollmentSchedule solution = solver.solve(problem);

                //Decide based on feasibility
                if (solution.getScore().isFeasible()) {
                    a.st.executeUpdate(a.enrollStud(id));
                    JOptionPane.showMessageDialog(null,
                            String.format("Student %s enrolled to %d", id, a.getsubjid()),
                            "enroll", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new Exception("Schedule conflict detected by OptaPlanner!");
                }

            }

            a.setsubjid(0);

        } catch (SQLException e) {
            System.out.println("Failed to enroll");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        ShowEnrollRec();
    }//GEN-LAST:event_jButton4ActionPerformed

    private Timeslot parseScheduleStringToTimeslot(String schedule, DateTimeFormatter formatter) {
        if (schedule == null || schedule.trim().isEmpty()) {
            return null;
        }
        try {
            String[] parts = schedule.split(" ");
            String day = parts[0];
            String[] timeParts = parts[1].split("-");
            LocalTime startTime = LocalTime.parse(timeParts[0], formatter);
            LocalTime endTime = LocalTime.parse(timeParts[1], formatter);
            return new Timeslot(day, startTime, endTime);
        } catch (Exception e) {
            System.err.println("Failed to parse schedule string: " + schedule);
            return null;
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Enrolled a = new Enrolled();        // TODO add your handling code here:
        int id = 0;
        int row = jTable1.getSelectedRow();
        if(row != -1){
            id = Integer.parseInt(String.valueOf(jTable1.getValueAt(row, 0)));
            System.out.println("ID: " + id);
        }
        
        try {
            a.st.executeUpdate(a.DropSubj(id));
            a.setsubjid(0);
        } catch (SQLException ex) {
            System.out.println("Failed to drop: " + ex);
        }
        
        ShowEnrollRec();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int id = 0;
        int row = jTable2.getSelectedRow();
        if(row != -1){
            id = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            System.out.println("ID: " + id);
        }
        Enrolled a = new Enrolled();        // TODO add your handling code here:
        a.setsubjid(id);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //createDB("1st");
        Students a = new Students();
        
        String getMax = "SELECT schema_name "
                + "FROM information_schema.schemata "
                + "WHERE schema_name REGEXP '^2nd_sy[0-9]{4}_[0-9]{4}$' "
                + "ORDER BY schema_name DESC "
                + "LIMIT 1";
        String input = "";
        
        try {
            a.rs = a.st.executeQuery(getMax);
            
            while(a.rs.next())
                input = a.rs.getString("SCHEMA_NAME");
        } catch (SQLException ex) {
            System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        int currYear = 0; // where we'll save the result
        String patternString = "sy(\\d{4})"; // regex pattern
        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(input);

        if (matcher.find()) {
            currYear = Integer.parseInt(matcher.group(1)) + 1; // save "2025" into the string variable
        }

        int nextYear = currYear + 1;
        String dbName = "2nd" + "_sy" + currYear + "_" + nextYear;

        String sql = "CREATE DATABASE `" + dbName + "`;";
        
        try {
            try (
                Statement stmt = con.createStatement()) {
                
                //create new database
                
                stmt.executeUpdate(sql);
                String tempDBUSE = "USE `" + dbName + "`;";
                String backDB = "USE `" + a.db + "`;";
                stmt.executeUpdate(tempDBUSE);

                //create student table
                sql = "CREATE TABLE students ("
                        + "studid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Course TEXT, "
                        + "Gender TEXT, "
                        + "Yearlvl TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create teacher's table
                sql = "CREATE TABLE teachers ("
                        + "Tid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Contact TEXT, "
                        + "Status TEXT, "
                        + "Dept TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create subjects table
                sql = "CREATE TABLE subjects ("
                        + "subjid INT PRIMARY KEY, "
                        + "SubjCode TEXT, "
                        + "SubjDesc TEXT, "
                        + "SubjUnits INT, "
                        + "Schedule TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create enroll
                sql = "CREATE TABLE enroll ("
                        + "eid INT PRIMARY KEY, "
                        + "studid INT, "
                        + "subjid INT, "
                        + "evaluation TEXT, "
                        + "FOREIGN KEY (studid) REFERENCES Students(studid),"
                        + "FOREIGN KEY (subjid) REFERENCES Subjects(subjid),"
                        + "UNIQUE (studid, subjid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create assign
                sql = "CREATE TABLE assign ("
                        + "subid INT, "
                        + "tid INT, "
                        + "FOREIGN KEY (subid) REFERENCES Subjects(subjid),"
                        + "FOREIGN KEY (tid) REFERENCES Teachers(Tid),"
                        + "UNIQUE (subid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create grades
                sql = "CREATE TABLE grades ("
                        + "GradeID INT PRIMARY KEY, "
                        + "eid INT, "
                        + "Prelim TEXT,"
                        + "Midterm TEXT, "
                        + "Prefinal TEXT, "
                        + "Final TEXT,"
                        + "FOREIGN KEY (eid) REFERENCES Enroll(eid),"
                        + "UNIQUE (eid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create TransactionCharges table
                sql = "CREATE TABLE TransactionCharges ("
                        + "TransID INT PRIMARY KEY, "
                        + "Department TEXT, "
                        + "SubjUnits DECIMAL(10,2), "
                        + "Insurance DECIMAL(10,2), "
                        + "Computer DECIMAL(10,2), "
                        + "Laboratory DECIMAL(10,2), "
                        + "Cultural DECIMAL(10,2), "
                        + "Library DECIMAL(10,2), "
                        + "Facility DECIMAL(10,2)"
                        + ");";
                stmt.executeUpdate(sql);

                //create invoice
                sql = "CREATE TABLE Invoice ("
                        + "Invoicenum INT PRIMARY KEY, "
                        + "studid INT, "
                        + "TransID INT,"
                        + "FOREIGN KEY(TransID) REFERENCES TransactionCharges(TransID),"
                        + "FOREIGN KEY(studid) REFERENCES Students(studid),"
                        + "UNIQUE (TransID)"
                        + ");";
                stmt.executeUpdate(sql);
                
                sql = """
                     CREATE PROCEDURE sched_Conf(IN studId INT, IN subid2 INT)
                     BEGIN
                         DECLARE subSched VARCHAR(20);
                         DECLARE subDays VARCHAR(10);
                         DECLARE subHoursStart VARCHAR(10);
                         DECLARE subMinutesStart VARCHAR(10);
                         DECLARE subHoursEnd VARCHAR(10);
                         DECLARE subMinutesEnd VARCHAR(10);
                         DECLARE subSched2 VARCHAR(20);
                         DECLARE subDays2 VARCHAR(10);
                         DECLARE subHoursStart2 VARCHAR(10);
                         DECLARE subMinutesStart2 VARCHAR(10);
                         DECLARE subHoursEnd2 VARCHAR(10);
                         DECLARE subMinutesEnd2 VARCHAR(10);
                         DECLARE noMoreSched INT DEFAULT 0;
                         DECLARE curSub CURSOR FOR
                             SELECT s.schedule
                             FROM enroll e
                             INNER JOIN subjects s ON e.subjid = s.subjid
                             WHERE e.studid = studId;
                         DECLARE curSub2 CURSOR FOR
                             SELECT schedule FROM subjects WHERE subjid = subid2;
                         DECLARE CONTINUE HANDLER FOR NOT FOUND SET noMoreSched = 1;
                         CREATE TEMPORARY TABLE conflicts (studid INT, subjid INT);
                         CREATE TABLE IF NOT EXISTS conflictMsg (msg VARCHAR(50));
                         DELETE FROM conflictMsg;
                         OPEN curSub;
                         sub1_loop: LOOP
                             FETCH curSub INTO subSched;
                             IF noMoreSched THEN
                                 LEAVE sub1_loop;
                             END IF;
                             SET subDays        = LEFT(subSched, 3);
                             SET subHoursStart  = SUBSTRING(subSched, 5, 2);
                             SET subMinutesStart= SUBSTRING(subSched, 8, 2);
                             SET subHoursEnd    = SUBSTRING(subSched, 11, 2);
                             SET subMinutesEnd  = SUBSTRING(subSched, 14, 2);
                             SET noMoreSched = 0;
                             OPEN curSub2;
                             sub2_loop: LOOP
                                 FETCH curSub2 INTO subSched2;
                                 IF noMoreSched THEN
                                     LEAVE sub2_loop;
                                 END IF;
                                 SET subDays2         = LEFT(subSched2, 3);
                                 SET subHoursStart2   = SUBSTRING(subSched2, 5, 2);
                                 SET subMinutesStart2 = SUBSTRING(subSched2, 8, 2);
                                 SET subHoursEnd2     = SUBSTRING(subSched2, 11, 2);
                                 SET subMinutesEnd2   = SUBSTRING(subSched2, 14, 2);
                                 SET @start1 = subHoursStart * 100 + subMinutesStart;
                                 SET @end1   = subHoursEnd   * 100 + subMinutesEnd;
                                 SET @start2 = subHoursStart2 * 100 + subMinutesStart2;
                                 SET @end2   = subHoursEnd2   * 100 + subMinutesEnd2;
                                 IF subDays = subDays2 AND @start1 < @end2 AND @start2 < @end1 THEN
                                     INSERT INTO conflicts VALUES (studId, subid2);
                                     INSERT INTO conflictMsg VALUES (CONCAT('Conflict with schedule: ', subSched));
                                 END IF;
                             END LOOP sub2_loop;
                             CLOSE curSub2;
                             SET noMoreSched = 0;
                         END LOOP sub1_loop;
                         CLOSE curSub;
                         -- DELETE FROM enroll WHERE (studid, subjid) IN (SELECT studid, subjid FROM conflicts);
                         DROP TEMPORARY TABLE conflicts;
                     END;
                    """;
                stmt.executeUpdate(sql);
                
                try {
                    studTeachSubCopy(dbName);
                    System.out.println("studTeachSubCopy BEING USED");
                } catch (Exception ex) {
                    System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                stmt.executeUpdate(backDB);
                //drop remaining users
            }
            JOptionPane.showMessageDialog(null, "Database `" + dbName + "` created successfully!");
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
         //createDB
        //showrecords();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        //createDB("1st");
        Students a = new Students();

        String getMax = "SELECT schema_name "
                + "FROM information_schema.schemata "
                + "WHERE schema_name REGEXP '^summer_sy[0-9]{4}_[0-9]{4}$' "
                + "ORDER BY schema_name DESC "
                + "LIMIT 1";
        String input = "";

        try {
            a.rs = a.st.executeQuery(getMax);

            while (a.rs.next()) {
                input = a.rs.getString("SCHEMA_NAME");
            }
        } catch (SQLException ex) {
            System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        int currYear = 0; // where we'll save the result

        String patternString = "sy(\\d{4})"; // regex pattern
        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(input);

        if (matcher.find()) {
            currYear = Integer.parseInt(matcher.group(1)) + 1; // save "2025" into the string variable
        }

        int nextYear = currYear + 1;
        String dbName = "summer" + "_sy" + currYear + "_" + nextYear;

        String sql = "CREATE DATABASE `" + dbName + "`;";
        try {
            try (Statement stmt = con.createStatement()) {
                
                
                //create new database
                stmt.executeUpdate(sql);
                String tempDBUSE = "USE `" + dbName + "`;";
                String backDB = "USE `" + a.db + "`;";
                stmt.executeUpdate(tempDBUSE);

                //create student table
                sql = "CREATE TABLE students ("
                        + "studid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Course TEXT, "
                        + "Gender TEXT, "
                        + "Yearlvl TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create teacher's table
                sql = "CREATE TABLE teachers ("
                        + "Tid INT PRIMARY KEY, "
                        + "Name TEXT, "
                        + "Address TEXT, "
                        + "Contact TEXT, "
                        + "Status TEXT, "
                        + "Dept TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create subjects table
                sql = "CREATE TABLE subjects ("
                        + "subjid INT PRIMARY KEY, "
                        + "SubjCode TEXT, "
                        + "SubjDesc TEXT, "
                        + "SubjUnits INT, "
                        + "Schedule TEXT"
                        + ");";
                stmt.executeUpdate(sql);

                //create enroll
                sql = "CREATE TABLE enroll ("
                        + "eid INT PRIMARY KEY, "
                        + "studid INT, "
                        + "subjid INT, "
                        + "evaluation TEXT, "
                        + "FOREIGN KEY (studid) REFERENCES Students(studid),"
                        + "FOREIGN KEY (subjid) REFERENCES Subjects(subjid),"
                        + "UNIQUE (studid, subjid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create assign
                sql = "CREATE TABLE assign ("
                        + "subid INT, "
                        + "tid INT, "
                        + "FOREIGN KEY (subid) REFERENCES Subjects(subjid),"
                        + "FOREIGN KEY (tid) REFERENCES Teachers(Tid),"
                        + "UNIQUE (subid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create grades
                sql = "CREATE TABLE grades ("
                        + "GradeID INT PRIMARY KEY, "
                        + "eid INT, "
                        + "Prelim TEXT,"
                        + "Midterm TEXT, "
                        + "Prefinal TEXT, "
                        + "Final TEXT,"
                        + "FOREIGN KEY (eid) REFERENCES Enroll(eid),"
                        + "UNIQUE (eid)"
                        + ");";
                stmt.executeUpdate(sql);

                //create TransactionCharges table
                sql = "CREATE TABLE TransactionCharges ("
                        + "TransID INT PRIMARY KEY, "
                        + "Department TEXT, "
                        + "SubjUnits DECIMAL(10,2), "
                        + "Insurance DECIMAL(10,2), "
                        + "Computer DECIMAL(10,2), "
                        + "Laboratory DECIMAL(10,2), "
                        + "Cultural DECIMAL(10,2), "
                        + "Library DECIMAL(10,2), "
                        + "Facility DECIMAL(10,2)"
                        + ");";
                stmt.executeUpdate(sql);

                //create invoice
                sql = "CREATE TABLE Invoice ("
                        + "Invoicenum INT PRIMARY KEY, "
                        + "studid INT, "
                        + "TransID INT,"
                        + "FOREIGN KEY(TransID) REFERENCES TransactionCharges(TransID),"
                        + "FOREIGN KEY(studid) REFERENCES Students(studid),"
                        + "UNIQUE (TransID)"
                        + ");";
                stmt.executeUpdate(sql);
                
                sql = """
                     CREATE PROCEDURE sched_Conf(IN studId INT, IN subid2 INT)
                     BEGIN
                         DECLARE subSched VARCHAR(20);
                         DECLARE subDays VARCHAR(10);
                         DECLARE subHoursStart VARCHAR(10);
                         DECLARE subMinutesStart VARCHAR(10);
                         DECLARE subHoursEnd VARCHAR(10);
                         DECLARE subMinutesEnd VARCHAR(10);
                         DECLARE subSched2 VARCHAR(20);
                         DECLARE subDays2 VARCHAR(10);
                         DECLARE subHoursStart2 VARCHAR(10);
                         DECLARE subMinutesStart2 VARCHAR(10);
                         DECLARE subHoursEnd2 VARCHAR(10);
                         DECLARE subMinutesEnd2 VARCHAR(10);
                         DECLARE noMoreSched INT DEFAULT 0;
                         DECLARE curSub CURSOR FOR
                             SELECT s.schedule
                             FROM enroll e
                             INNER JOIN subjects s ON e.subjid = s.subjid
                             WHERE e.studid = studId;
                         DECLARE curSub2 CURSOR FOR
                             SELECT schedule FROM subjects WHERE subjid = subid2;
                         DECLARE CONTINUE HANDLER FOR NOT FOUND SET noMoreSched = 1;
                         CREATE TEMPORARY TABLE conflicts (studid INT, subjid INT);
                         CREATE TABLE IF NOT EXISTS conflictMsg (msg VARCHAR(50));
                         DELETE FROM conflictMsg;
                         OPEN curSub;
                         sub1_loop: LOOP
                             FETCH curSub INTO subSched;
                             IF noMoreSched THEN
                                 LEAVE sub1_loop;
                             END IF;
                             SET subDays        = LEFT(subSched, 3);
                             SET subHoursStart  = SUBSTRING(subSched, 5, 2);
                             SET subMinutesStart= SUBSTRING(subSched, 8, 2);
                             SET subHoursEnd    = SUBSTRING(subSched, 11, 2);
                             SET subMinutesEnd  = SUBSTRING(subSched, 14, 2);
                             SET noMoreSched = 0;
                             OPEN curSub2;
                             sub2_loop: LOOP
                                 FETCH curSub2 INTO subSched2;
                                 IF noMoreSched THEN
                                     LEAVE sub2_loop;
                                 END IF;
                                 SET subDays2         = LEFT(subSched2, 3);
                                 SET subHoursStart2   = SUBSTRING(subSched2, 5, 2);
                                 SET subMinutesStart2 = SUBSTRING(subSched2, 8, 2);
                                 SET subHoursEnd2     = SUBSTRING(subSched2, 11, 2);
                                 SET subMinutesEnd2   = SUBSTRING(subSched2, 14, 2);
                                 SET @start1 = subHoursStart * 100 + subMinutesStart;
                                 SET @end1   = subHoursEnd   * 100 + subMinutesEnd;
                                 SET @start2 = subHoursStart2 * 100 + subMinutesStart2;
                                 SET @end2   = subHoursEnd2   * 100 + subMinutesEnd2;
                                 IF subDays = subDays2 AND @start1 < @end2 AND @start2 < @end1 THEN
                                     INSERT INTO conflicts VALUES (studId, subid2);
                                     INSERT INTO conflictMsg VALUES (CONCAT('Conflict with schedule: ', subSched));
                                 END IF;
                             END LOOP sub2_loop;
                             CLOSE curSub2;
                             SET noMoreSched = 0;
                         END LOOP sub1_loop;
                         CLOSE curSub;
                         -- DELETE FROM enroll WHERE (studid, subjid) IN (SELECT studid, subjid FROM conflicts);
                         DROP TEMPORARY TABLE conflicts;
                     END;
                    """;
                stmt.executeUpdate(sql);
                
                
                try {
                    studTeachSubCopy(dbName);
                    System.out.println("ENROLLTRAIN BEING USED");
                } catch (Exception ex) {
                    System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                
                stmt.executeUpdate(backDB);
                
            }
            JOptionPane.showMessageDialog(null, "Database `" + dbName + "` created successfully!");
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
        
        System.out.println("ENROLL TRAIN NOT USED");
         //createDB
        //showrecords();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void TORbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TORbuttonActionPerformed
        // TODO add your handling code here:
        Reports a = new Reports();
        int row = jTable1.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }
        
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String name = jTable1.getValueAt(row, 1).toString();
        String course = jTable1.getValueAt(row, 3).toString();
        String gender = jTable1.getValueAt(row, 4).toString();
        
        System.out.println(name);
        
        a.createReportRoot(id, name, course, gender);
    }//GEN-LAST:event_TORbuttonActionPerformed

    private void aiEnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiEnrollButtonActionPerformed
        // TODO add your handling code here:
        
        Predictions b = new Predictions();
        int row = jTable1.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        }
        
        String studid = jTable1.getValueAt(row, 0).toString();
        try {
            b.predictEnroll(studid, db);
        } catch (Exception ex) {
            System.getLogger(StudentsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        ShowEnrollRec();
    }//GEN-LAST:event_aiEnrollButtonActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        schoolyear a = new schoolyear();
        
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    
    public static int optaPlannerActivator;
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        optaPlannerActivator++;
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    
    public void showrecords(){
        String query = "SELECT * FROM Students;";
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        model.setRowCount(0);
        
        try {
            Students.rs = Students.st.executeQuery(query);
            studRegLabel.setText("Student Registration System: " + Students.db);
            
            while (Students.rs.next()) {
                String id = Students.rs.getString("studid");
                String name = Students.rs.getString("Name");
                String add = Students.rs.getString("Address");
                String course = Students.rs.getString("Course");
                String gender = Students.rs.getString("Gender");
                String year = Students.rs.getString("yearLvl");
                String[] items = {id, name, add, course, gender, year};
                model.addRow(items);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void ShowEnrollRec(){
       
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        int studentId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String query = "SELECT * FROM Subjects WHERE subjid IN " +
                   "(SELECT subjid FROM Enroll WHERE studid = " + studentId + ");";
        DefaultTableModel model = ((DefaultTableModel) jTable2.getModel());
        model.setRowCount(0);
        
        try {
            Enrolled.rs = Enrolled.st.executeQuery(query);
            
            while(Enrolled.rs.next()) {
                String id = Enrolled.rs.getString("subjid");
                String code = Subjects.rs.getString("SubjCode");
                String desc = Subjects.rs.getString("SubjDesc");
                String units = Subjects.rs.getString("SubjUnits");
                String sched = Subjects.rs.getString("Schedule");
                String[] items = {id, code, desc, units, sched};
                model.addRow(items);
            }
            
        } catch(Exception ex){
            System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Course;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Name;
    private javax.swing.JButton TORbutton;
    private javax.swing.JTextField Yearlvl;
    private javax.swing.JButton aiEnrollButton;
    private javax.swing.JMenu aiMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel studRegLabel;
    private javax.swing.JTextField studid;
    // End of variables declaration//GEN-END:variables
}
