/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biruarenrollmentsystem;

//import static com.mycompany.biruarenrollmentsystem.Utility.loadRecord;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.db;
import static com.mycompany.biruarenrollmentsystem.BiruarEnrollmentSystem.st;
import java.awt.Point;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mxebiruar
 */
public class TeachersForm extends javax.swing.JFrame {

    /**
     * Creates new form TeachersForm
     */
    public TeachersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherRegLabel = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        Dept = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        teacherRegLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        teacherRegLabel.setForeground(new java.awt.Color(0, 153, 255));
        teacherRegLabel.setText("Teacher Registration");

        Tid.setEditable(false);
        Tid.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TidActionPerformed(evt);
            }
        });

        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });

        jLabel3.setText("Address");

        jLabel1.setText("Teacher ID");

        jLabel2.setText("Name");

        jLabel4.setText("Contact");

        jLabel5.setText("Status");

        jLabel6.setText("Department");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Contact", "Status", "Department"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "subjid", "SubjCode", "SubjDesc", "SubjUnits", "Schedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Assigned Subjects");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButton4.setText("Assign Subject");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete Subject");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Status, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Contact, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Address, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherRegLabel)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(teacherRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(449, 449, 449)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TidActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Teachers a = new Teachers();        // TODO add your handling code here:
        try {  
            a.SaveRecord(Tid.getText(), Name.getText(), Address.getText(),
                    Contact.getText(), Status.getText(), Dept.getText());
        } catch (SQLException ex) {
            System.getLogger(TeachersForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        showrecords();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       showrecords(); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Teachers a = new Teachers();        // TODO add your handling code here:
            a.UpdateRecord(Integer.parseInt(Tid.getText()), Name.getText(), Address.getText(),  
                    Contact.getText(), Status.getText(), Dept.getText());
        showrecords();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Teachers a = new Teachers();        // TODO add your handling code here:
            a.DeleteRecord(Integer.parseInt(Tid.getText()));
        showrecords();
        
        String query2 = "DELETE FROM Assign WHERE tid =" + Integer.parseInt(Tid.getText()) + ";";
        try {
            Assign.st.executeUpdate(query2);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        int id = Integer.parseInt(Tid.getText().trim());
        String name = Name.getText().trim();
        
        boolean exists = false;
        try (ResultSet rs = BiruarEnrollmentSystem.st.executeQuery("SHOW DATABASES")) {
            while (rs.next()) {
                String dbName = rs.getString("Database"); //get database name

                // only check AY databases
                if (!dbName.matches("^(1st|2nd|summer)_sy\\d{4}_\\d{4}$")) {
                    continue;
                }

                String check = "SELECT 1 FROM `" + dbName + "`.Teachers WHERE Tid = ? LIMIT 1";
                try (PreparedStatement ps = BiruarEnrollmentSystem.con.prepareStatement(check)) {
                    ps.setInt(1, id);
                    try (ResultSet r = ps.executeQuery()) {
                        if (r.next()) {
                            exists = true; // teacher still exists somewhere
                            break;
                        }
                    }
                } catch (SQLException ignore) {
                    // ignore missing tables/dbs
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error checking databases: " + ex);
        }

        if (!exists) {
            try {
                a.st.executeUpdate("DROP USER IF EXISTS '" + (id + name) + "'@'localhost';");
                System.out.println("User " + (id + name) + " dropped from MySQL.");
            } catch (SQLException ex) {
                System.out.println("Failed to delete user from mysql.user: " + ex);
            }
        } else {
            //REVOKE privilege_type [(column_list)] ON [object_type] privilege_level FROM user_account [, user_account] ...;
            String uName = id + name;
            String revokeQuery = String.format("REVOKE SELECT ON `" + db + "`.* FROM '%s'@'localhost';", uName);
            try {
                st.executeUpdate(revokeQuery);
                System.out.println("Teacher REVOKED on " + db);
            } catch (SQLException ex) {
                System.out.println("Error: " + ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        JTextField[] a = {Tid, Name, Address, Contact, Status, Dept};
        
        //loadRecord(jTable1, a, evt.getPoint());
        Point point = evt.getPoint();
        int row = jTable1.rowAtPoint(point);
        int col = jTable1.columnAtPoint(point);
        if(col == 0){
            for(int i = 0; i < jTable1.getColumnCount()-3; i++){
                a[i].setText(String.valueOf(jTable1.getValueAt(row,i)));
            }
        }
        a[3].setText("");
        a[4].setText("");
        a[5].setText("");
        
        //loadRecord
        ShowAssignRec();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int id = 0;
        int row = jTable2.getSelectedRow();
        if(row != -1){
            id = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
            System.out.println("ID: " + id);
        }
        Assign a = new Assign();        // TODO add your handling code here:
        a.setsubjid(id);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Assign a = new Assign();        
        int id = 0;
        int row = jTable1.getSelectedRow();
        if(row != -1){
            id = Integer.parseInt(String.valueOf(jTable1.getValueAt(row, 0)));
            System.out.println("ID: " + id);
        }

        try {
            a.st.executeUpdate(a.AssignSubj(id));
            a.setsubjid(0);
        } catch (SQLException ex) {
            System.out.println("Failed to assign: " + ex);
        }

        ShowAssignRec();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Assign a = new Assign();        // TODO add your handling code here:
        int id = 0;
        int row = jTable1.getSelectedRow();
        if(row != -1){
            id = Integer.parseInt(String.valueOf(jTable1.getValueAt(row, 0)));
            System.out.println("ID: " + id);
        }

        try {
            a.st.executeUpdate(a.DeleteSubj(id));
            a.setsubjid(0);
        } catch (SQLException ex) {
            System.out.println("Failed to delete: " + ex);
        }

        ShowAssignRec();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public void showrecords(){
        String query = "SELECT * FROM Teachers;";
        
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        model.setRowCount(0);
        
        try {
            Teachers.rs = Students.st.executeQuery(query);
            teacherRegLabel.setText("Teacher Registration System: " + Teachers.db);
            
            while (Teachers.rs.next()) {
                String id = Teachers.rs.getString("Tid");
                String name = Teachers.rs.getString("Name");
                String address = Teachers.rs.getString("Address");
                String contact = Teachers.rs.getString("Contact");
                String status = Teachers.rs.getString("Status");
                String dept = Teachers.rs.getString("Dept");
                String[] items = {id, name, address, contact, status, dept};
                model.addRow(items);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void ShowAssignRec(){
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        int tid = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String query = "SELECT * FROM Subjects WHERE subjid IN " +
                   "(SELECT subid FROM Assign WHERE tid = " + tid + ");";
        DefaultTableModel model = ((DefaultTableModel) jTable2.getModel());
        model.setRowCount(0);
        
        try {
            Assign.rs = Assign.st.executeQuery(query);
            
            while(Assign.rs.next()) {
                String id = Assign.rs.getString("subjid");
                String code = Subjects.rs.getString("SubjCode");
                String desc = Subjects.rs.getString("SubjDesc");
                String units = Subjects.rs.getString("SubjUnits");
                String sched = Subjects.rs.getString("Schedule");
                String[] items = {id, code, desc, units, sched};
                model.addRow(items);
            }
            
        } catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //java.util.logging.Level.SEVERE, null, ex
        //javEmaillogging.Level.SEVERE, null, ex (changed on line 279)
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Dept;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Tid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel teacherRegLabel;
    // End of variables declaration//GEN-END:variables
}
